#!/bin/bash
echo "Compile and run...."
if [ $# -eq 0 ]; then
    echo "No arguments provided, looper.cpp will be used"
    filename=looper.cpp
else
   filename=$1
fi

if [[ $filename -nt ./main ]]; then
  g++-10 -I /home/dmitriy/projects/shared/C++ -std=c++2a -Dexpclos $filename -lstdc++ -o main
  retVal=$?
else
  retVal=0
fi
if [ $retVal == 0 ]; then
    ./main $2
fi

