#!/bin/bash
echo "Compile and run...."
if [ $# -eq 0 ]; then
    echo "No arguments provided, looper.cpp will be used"
    filename=looper.cpp
else
   filename=$1
fi

if [[ $filename -nt "./${filename%.*}" ]]; then
  g++ -Ofast -I /home/dmitriy/projects/shared/C++ -std=c++2a -Dexpclos $filename -lstdc++ -o ${filename%.*}
  retVal=$?
else
  retVal=0
fi
if [ $retVal == 0 ]; then
    time "./${filename%.*}" $2
fi

